### ISSUE TITLE
Simple Graphs

### ISSUE THREAD

**Issue by johnRedden** [pgonzbecer/SurgeWebSite#11]
The sample graphs app got goofed up somehow. Needs fixing... 

https://rawgit.com/pgonzbecer/SurgeWebSite/master/graphs/SinGraph.html

**Comment by pgonzbecer** [comment]
Seems like a classic case of merging errors, done

**Comment by mecharmor** [comment]
Got little confused.
Your email split up into 5 or 6 emails for me.
Just want to confirm these:
So we dont have another meeting?
the website is done. Other than the stuff I touched up on.
And when is the display day thing where we present our app?

----- Reply message -----
