### ISSUE TITLE
Calculator Footer

### ISSUE THREAD

**Issue by johnRedden** [pgonzbecer/SurgeWebSite#13]
The footer on the calculators page does not match all of the other footers.

https://rawgit.com/pgonzbecer/SurgeWebSite/master/calculators.html

Missing a horizontal rule <hr> or something.

**Comment by mecharmor** [comment]
I don't have internet for my laptop at the moment so when I am able to go to a coffee shop or something with free WiFi then I will try to get some stuff done on it.

Sent from Cory's phone.

----- Reply message -----

**Comment by pgonzbecer** [comment]
done
