### ISSUE TITLE
Technology page

### ISSUE THREAD

**Issue by johnRedden** [pgonzbecer/SurgeWebSite#15]
In the about dropdown we should add another page... technology.  A page about the technology that we have used.  DART, HTML5, JAVASCRIPT, JQUERY, jsxGraph, and Bootstrap.

I will do this.

**Comment by johnRedden** [comment]
Made the page and added the link in the nav across the board.  Still need to add a snip for each and clean up the wording.

**Comment by pgonzbecer** [comment]
I put up the logos, jsxgraph doesn't have anything to it, so I left it alone, and I think the wording on it is good enough as is for closure
