### ISSUE TITLE
Algebra in the Navbar does not highlight 

### ISSUE THREAD

**Issue by johnRedden** [pgonzbecer/SurgeWebSite#18]
When the algebra page is clicked Algebra in the nav should highlight... like all the other pages.

**Comment by mecharmor** [comment]
im having syncing issues on github so i will bring my fixed work to our last meeting and have you or paul help me sync it correctly.also when is our next meeting?  date & time
Things i have Fixed but not yet synced:-Footer on calculators page- fixed my bio page up a little bit-fixed highlighting issue on the algebra page-added a footer to the algebra page

```
  From: John Redden <notifications@github.com>
```

 To: pgonzbecer/SurgeWebSite SurgeWebSite@noreply.github.com 
 Sent: Friday, August 7, 2015 3:53 PM
 Subject: [SurgeWebSite] Algebra in the Navbar does not highlight (#18)

When the algebra page is clicked Algebra in the nav should highlight... like all the other pages.—

**Comment by pgonzbecer** [comment]
done, and I don't know when our next meeting is :S
